package com.mycompany.bibliotecadigital;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Libro;

public class LibroPanel extends javax.swing.JPanel {

    private final Libro libro;

    public LibroPanel(Libro libro) {
        initComponents();
        this.libro = libro;
        mostrarDetallesLibro();
    }
    
    private void mostrarDetallesLibro() {
        System.out.println("Mostrando detalles del libro: " + libro.getTitulo() + " - " + libro.getAutor());

        ImageIcon icon = null;
        String imagenPath = libro.getImagenPath();

        if (imagenPath != null && !imagenPath.isEmpty()) {
            System.out.println("Ruta de imagen: " + imagenPath);
            icon = new ImageIcon(imagenPath);
        } else {
            System.out.println("No se encontró ruta de imagen válida, utilizando imagen por defecto.");
            icon = new ImageIcon(getClass().getResource("src/main/resources/libro1.jpg"));
        }

        Image img = icon.getImage().getScaledInstance(299, 466, Image.SCALE_SMOOTH);
        jlImagen.setIcon(new ImageIcon(img));
        jlTitulo.setText(libro.getTitulo());
        jlAutor.setText(libro.getAutor());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlImagen = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbLeer = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlAutor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlAutor.setForeground(new java.awt.Color(7, 15, 43));

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(7, 15, 43));

        jbLeer.setBackground(new java.awt.Color(7, 15, 43));
        jbLeer.setForeground(new java.awt.Color(255, 255, 255));
        jbLeer.setText("Leer");
        jbLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLeerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                            .addComponent(jlAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jlAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLeerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbLeer;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlImagen;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
